workflows:
  ios-release:
    name: iOS Release
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic # Must match your Team Integration name
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.pahal.lc"
    scripts:
      - name: Set up compiler dependencies
        script: flutter pub get

      - name: Fetch and Install Apple Certificates/Profiles
        script: xcode-project use-profiles --archive-method=app-store

      - name: Build Flutter IPA
        script: flutter build ipa --release --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
